### ISSUE TITLE
RCTBridgeModule.h file not found

### ISSUE THREAD

**Issue by ghost** [booxood/react-native-file-upload#10]
In XCode, in the project navigator, right click your project ➜ Add Files to [your project's name]
Go to node_modules ➜ react-native-fileupload and add FileUpload.m
Run your project (Cmd+R)
Followed this step and stuck at this error. i am checking this module on ios.

**Comment by booxood** [comment]
React Native latest version had support file upload, the package is deprecated, detail see #4 #7.
