### ISSUE TITLE
Improvements over built-in XHR + FormData?

### ISSUE THREAD

**Issue by philikon** [booxood/react-native-file-upload#4]
This is great, but I was wondering if `react-native-file-upload` provided any improvements over the functionality provided in React Native proper, and if so, what. A few months ago I polyfilled `XMLHttpRequest` and `FormData` so that file upload scenarios should be possible, on both iOS and Android. Check out https://github.com/facebook/react-native/blob/fe42a28de12926c7b3254420ccb85bef5f46327f/Examples/UIExplorer/XHRExample.ios.js#L215-L230 for instance.

If there _is_ anything that's missing from React Native, I'd love to hear about it. It'd be great to get those features into React Native. Thanks!

cc @booxood @PhilippKrone

**Comment by booxood** [comment]
@philikon 

No Improvements, only to support file upload for `React Native` old version. If now `React Native` have been provided that it is really nice!

Maybe can add some suggestions for the new version of user.

**Comment by gorjanz** [comment]
Isn't the difference that this module uploads the image directly from native part of the app, without transferring the photo through the bridge, and uploading it from js?

@philikon can you please provide an explanation how the upload works internally? I am trying to implement a simple upload of image, which I have previously saved to the camera roll, and understanding this would help me a lot. Thanks.

**Comment by gorjanz** [comment]
@philikon 

update: No need, found this: https://github.com/facebook/react-native/blob/72b274a9b94a256431e595446a54bcc6eb2192a8/docs/Network.md which explains a lot. Thanks for implementing this. Great work.

**Comment by gorjanz** [comment]
@philikon 
Can you please advise me how to actually upload the image, as multipart binary data, instead of uploading the details for the image, as in the example? Thanks.
