### ISSUE TITLE
Can't get image data

### ISSUE THREAD

**Issue by wengbenjue** [booxood/react-native-file-upload#5]
I use spray+akka restful as server
this is data server recieved
MultipartFormData(Vector(BodyPart(HttpEntity(text/plain; charset=UTF-8,world),List(Content-Disposition: form-data; name=hello)), BodyPart(Empty,List(Content-Length: 0, Content-Type: image/png,image/gif,image/jpeg, Content-Disposition: form-data; name=one; filename=FAE2F476-6BF0-4F0B-8D1D-E478CDF1C9DB.jpg))))

from here,I just get Empty,cant't get image binary data

this is my client react native,Does there some question?Thanks

 constructor(props) {
        super(props);
        this.state = {
            avatarSource: null,
            videoSource: null
        };
        var obj = {
            uploadUrl: 'http://127.0.0.1:8080/soledede/image',
            method: 'POST', // default 'POST',support 'POST' and 'PUT'
            headers: {
                'Accept': 'application/json',
                //'Accept': 'multipart/form-data',
                //'Content-type': 'multipart/form-data'
                //'Content-Disposition': 'form-data; name="file"',
            },
            fields: {
                'hello': 'world',
            },
            files: [
                {
                    name: 'one', // optional, if none then `filename` is used instead
                    filename: 'FAE2F476-6BF0-4F0B-8D1D-E478CDF1C9DB.jpg', // require, file name
                    filepath: 'file:///Users/soledede/Library/Developer/CoreSimulator/Devices/6686658C-D8D8-4445-9790-C035F01DA880/data/Containers/Data/Application/8D092B09-5AA4-4445-A7F2-68D45C0537ED/Documents/FAE2F476-6BF0-4F0B-8D1D-E478CDF1C9DB.jpg', // require, file absoluete path
                    filetype: 'image/png,image/gif,image/jpeg', // options, if none, will get mimetype from `filepath` extension
                },
            ]
        };
        FileUpload.upload(obj, function (err, result) {
            console.log('upload:', err, result);
        });
    }

**Comment by booxood** [comment]
Your `filepath` is how to get? I think should be the `filepath` question. Maybe you can look at the [code here](https://github.com/booxood/react-native-file-upload/blob/master/FileUpload.m#L99).

**Comment by wengbenjue** [comment]
Actually,It is,In IOS,I can upload image,but I still can't upload image binary in android.

here is my android file path

  constructor(props) {
        super(props);
        this.state = {
            avatarSource: null,
            videoSource: null
        };
        var obj = {
            uploadUrl: 'http://192.168.50.161:8080/soledede/image',
            method: 'POST', // default 'POST',support 'POST' and 'PUT'
            headers: {
                'Accept': 'application/json',
                //'Accept': 'multipart/form-data',
                //'Content-type': 'multipart/form-data'
                //'Content-Disposition': 'form-data; name="file"',
            },
            fields: {
                'hello': 'world',
            },
            files: [
                {
                    name: 'image', // optional, if none then `filename` is used instead
                    filename: '1007044', // require, file name  
                    filepath: 'content://media/external/images/media/1007044', // require, 
                    filetype: 'image/png,image/gif,image/jpeg', 
                },
            ]
        };
        FileUpload.upload(obj, function (err, result) {
            console.log('upload:', err, result);
        });
    }

# 

there is my debug in chrome
![image](https://cloud.githubusercontent.com/assets/5533297/12313065/6b2e0994-ba9f-11e5-9b1c-c88944ce2cce.png)

How can I deal with it in android

Thanks

soledede

**Comment by booxood** [comment]
Not support android. In #3 have discuss. You can use https://github.com/PhilippKrone/react-native-fileupload.
