### ISSUE TITLE
How to upload by asset-library in IOS

### ISSUE THREAD

**Issue by wengbenjue** [booxood/react-native-file-upload#6]
My uri is 'assets-library://asset/asset.JPG?id=ADDB18BD-F81E-4C64-BB05-D994F0D53F8D&ext=JPG'

How can I upload image by this

Thanks

**Comment by booxood** [comment]
Assign to `filepath`.

**Comment by wootwoot1234** [comment]
It's untested but I forked this code and added assets-library support.

https://github.com/wootwoot1234/react-native-transfer
