### ISSUE TITLE
Error on 201

### ISSUE THREAD

**Issue by Wasseing** [booxood/react-native-file-upload#8]
Got an error when the server is responding `201`  

maybe because line 143 FileUploadodule.java this test is not enough. 

`if (serverResponseCode != 200)`

**Comment by booxood** [comment]
what's `FileUploadodule.java`❓

**Comment by Wasseing** [comment]
under `node_modules/react-native-fileupload/android/src/main.../FileUploadModule.java`

**Comment by booxood** [comment]
is not this package
